- I want to learn how to code a 2D action RPG that will be fun for me and my friends to play
- I will get satisfaction that my friends will be able to play
- I will learn in my office at 8 am
- 30 mins to 1 hour
- I will avoid distractions by closing all windows and play relaxing music
- By getting my friends to play test my game and give me feedback
